services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"  # API port
      - "9090:9090"  # Console port
    env_file:
      - .env.properties
    environment:
      # Auth (from your auth.rootUser / rootPassword)
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      # Extra Env Vars
      - MINIO_DOMAIN=minio-release.storage.svc.cluster.local
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    # Persistence: false (Uses ephemeral container memory/storage)
    tmpfs:
      - /data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 500M